---
# Source: helm for kubernetes/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fsdf-5eec03f2
  labels:
    app: fsdf-5eec03f2
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: fsdf-5eec03f2
  template:
    metadata:
      labels:
        app: fsdf-5eec03f2
    spec:
      serviceAccountName: ingress-manager
      containers:
        - name: fsdf-5eec03f2
          image: docker.io/phengbunath/fsdf-5eec03f2:1
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
