---
# Source: helm for kubernetes/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: fsdf-5eec03f2          # Service name
  labels:
    app: fsdf-5eec03f2
spec:
  type: ClusterIP   # Service type (ClusterIP, NodePort, LoadBalancer)
  selector:
    app: fsdf-5eec03f2         # Matches Deployment labels
  ports:
    - protocol: TCP
      port: 3000         # Service port
      targetPort: 3000  # Target container port
